algoritmo "Questao_10"
// Função :
// Autor :
// Data : 19/03/2020
// Seção de Declarações 
var
   idade: inteiro
   nome: caracter
   total_dias: inteiro
   

inicio
// Seção de Comandos 
    escreval("Qual o seu nome")
    leia(nome)
    escreval("Qual sua idade")
    leia(idade)
    
    total_dias <- idade * 12 * 30
    
    escreva("Voce viveu ", total_dias, " dias")


fimalgoritmo
