algoritmo "questao_9"
var
          largura, comprimento, area, valor : real

inicio
          escreval("Qual a largura?")
          leia(largura)
          escreval("Qual o comprimento?")
          leia(comprimento)
          
          area <- largura*comprimento
          escreval("A area do tereno é ",area)
          
          valor <- area *530
          escreval("O valor de venda é ",valor)

fimalgoritmo
